[project]
name = "franka-desk-api-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.4",
]

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"
